# Generated by Django 4.2.11 on 2026-03-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидает'), ('confirmed', '✅ Подтверждено'), ('completed', '💈 Завершено'), ('cancelled', '❌ Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('unpaid', '💵 Не оплачено'), ('prepaid', '💳 Предоплата'), ('paid', '✅ Оплачено')], default='unpaid', max_length=20, verbose_name='Оплата')),
                ('promo_code', models.CharField(blank=True, max_length=20, verbose_name='Промокод')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('specialty', models.CharField(default='Стрижки', max_length=200, verbose_name='Специализация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='Фото')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Барбер',
                'verbose_name_plural': 'Барберы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('language', models.CharField(default='ru', max_length=5, verbose_name='Язык')),
                ('loyalty_points', models.IntegerField(default=0, verbose_name='Баллы лояльности')),
                ('referral_code', models.CharField(blank=True, max_length=20, verbose_name='Реф. код')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discount_percent', models.IntegerField(default=10, verbose_name='Скидка (%)')),
                ('promo_code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Конец')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции 🎁',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена (сом)')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Длительность (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги (Прайс)',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('text', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barbershop.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы ⭐',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.barber', verbose_name='Барбер'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop.service', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(default='10:00', verbose_name='Начало работы')),
                ('end_time', models.TimeField(default='20:00', verbose_name='Конец работы')),
                ('slot_duration', models.IntegerField(default=30, verbose_name='Длит. слота (мин)')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='barbershop.barber', verbose_name='Барбер')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'unique_together': {('barber', 'day_of_week')},
            },
        ),
    ]
